name: Upgrade Elementor test

on:
  push:
    branches:
      - 'main'
      - '3.[0-9][0-9]'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/config.json'
      - 'bin/**'
      - '.gitignore'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Elementor version from WordPress svn'
        required: false
        default: ''

jobs:
  build-plugin:
    uses: ./.github/workflows/build.yml
  run-upgrade-test:
    name: Playwright plugin upgrade test
    runs-on: ubuntu-22.04
    needs: [build-plugin]
    if: ${{ github.event.pull_request.title == null || needs.build-plugin.outputs.changelog_diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: |
          set -euo pipefail
          npm run prepare-environment:ci
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-plugin.outputs.artifact_name }}
          path: ./build

      - name: Install WordPress environment
        run: |
          set -euo pipefail
          npm run setup-templates
          npx wp-lite-env start --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --port=8888

      - name: Wait for WordPress to be ready
        run: |
          set -euo pipefail
          for i in {1..60}; do
            if curl -sSf http://localhost:8888/wp-login.php >/dev/null; then
              echo "WordPress is ready"
              exit 0
            fi
            echo "Waiting for WordPress... ($i/60)"
            sleep 2
          done
          echo "WordPress failed to start"
          exit 1
      - name: Setup test data
        run: |
          set -euo pipefail
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp theme delete hello-elementor --quiet || true" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp theme install https://downloads.wordpress.org/theme/hello-elementor.zip --activate --force" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp plugin install elementor --activate" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="bash elementor-config/setup.sh" --port=8888
      - name: WordPress debug information
        run: |
          set -euo pipefail
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp core version" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp --info" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp plugin list" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp theme list" --port=8888
      - name: Install Playwright browser & deps
        run: |
          set -euo pipefail
          npx playwright install-deps
          npx playwright install chromium
      - name: Upgrade site
        run: |
          set -euo pipefail
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp plugin install ./build --force" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp rewrite structure '/%postname%/' --hard && wp rewrite flush --hard" --port=8888
          npx wp-lite-env cli --config=./tests/playwright/upgrade-test/.upgrade-test-wp-lite-env.json --command="wp plugin list" --port=8888
      - name: Run Playwright tests
        run: |
          set -euo pipefail
          npm run test:playwright:elements-regression -- --grep="Test heading template"
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-elements-regression
          path: test-results/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright HTML report (if generated)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 7

  test-result:
    needs: run-upgrade-test
    if: ${{ always() }} # Will be run even if 'Playwright' matrix will be skipped
    runs-on: ubuntu-22.04
    name: Playwright - Test Results
    steps:
      - name: Test status
        run: echo "Test status is - ${{ needs.run-upgrade-test.result }}"
      - name: Check Playwright job status
        if: ${{ needs.run-upgrade-test.result != 'success' && needs.run-upgrade-test.result != 'skipped' }}
        run: exit 1
